### ISSUE TITLE
Add explicit prohibition against photographing sleeping people

### ISSUE THREAD

**Issue by nquinlan** [MLH/policies#5]
While we've encouraged and enforced a policy of no photographs of sleeping people, it hasn't been explicitly stated in the CoC. This should be added, perhaps borrowing from The Hack CoC.

> Photography is encouraged, but other participants must be given a reasonable chance to opt out from being photographed. If they object to the taking of their photograph, comply with their request. It is inappropriate to take photographs in contexts where people have a reasonable expectation of privacy (in bathrooms or where participants are sleeping).
> – [The Hack Code of Conduct](http://hackcodeofconduct.org/)

**Comment by theycallmeswift** [comment]
This is already included in the examples of harassment and is included in our official photographer communications, no need to flush this out further.
